### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by kosirm** [haritzmedina/hypothesis-api-client#21]
Hi, first of all thank you for publishing this library!
I would like to use it in [vitepress](https://github.com/vuejs/vitepress) project which is built on top of [vite](https://github.com/vitejs/vite), so I'm limited to ES6 imports.
Do you think I can just run cjs-to-es6 on whole library?

**Comment by haritzmedina** [comment]
Hi @kosirm,

First of all thank you for your interest in this library. As far as I know, you won't have any kind of problems just importing the library using ES6 imports. We are using it in some of our own projects without any kind of problems.

https://github.com/onekin/WacLine/blob/f7a30033a3b899467a2259cabd62172605aff22e/input/app/scripts/annotationServer/hypothesis/HypothesisClientManager.js#L3

However, they are used on client side, so we use babel and webpack to make it compatible in browsers, returning it back to ES5.

You can just try to fork the project and run cjs-to-es6 if simple import is not working for your use case in vitepress. In case cjs-toes6 works properly, please open a pull request and I will update the library to make it fully compatible with ES6.

Thanks,

**Comment by kosirm** [comment]
Thank you. I actually gave up on using hypothesis with vitepress, because I also have problems importing hypothesis client, problems with routing, etc. Anyway I tried to run cjs-to-es6 on your library and this is result: files in folder lib (Config.js and index.js) were successfully converted, but files in folder utils were skipped, I can't figure out why, I'm not really javascript expert, sorry.

**Comment by haritzmedina** [comment]
It seems that it worked as expected, the only file you would require to convert is the index.js, the others are simply utils that you can run from the command line as NodeJS apps.

However, I have seen your thread in [hypothesis-dev channel](https://groups.google.com/a/list.hypothes.is/g/dev/c/OZEBSDl-6PY/m/bd9FyOdZAwAJ). I'm not sure what are you planning to do (with vitepress and hypothes.is), but it seems that you want to augment/integrate hypothes.is UI to your vitepress website. In that case, my library is not for that purpose, it is a wrapper to retrieve/write annotations programatically using [their API](https://h.readthedocs.io/en/latest/api). To this end, I would recommend you to inject the [hypothesis client](https://hypothes.is/embed.js) (as @robertknight answered to you in that thread).

**Comment by kosirm** [comment]
Thank you! My project is kind a two-fold, I would like to integrate hypothesis client for creating annotations and on the other hand I would like to make a small UI for browsing annotations sitewide (this is currently the main limitation of hypothesis - you can see only page annotations). You can use their nice search page, but I would like to make a little "annotation manager" on my site. This is the part where I want to use your library.
I actually gave up on using Vite for this, because Vite [relies on latest JS functionality straight from the browser](https://harlanzw.com/blog/how-the-heck-does-vite-work/) (Native-ES-Module), so it's just not compatible with hypothesis client. So I will an use your library as it is. Thank you again for your support!

**Comment by haritzmedina** [comment]
Yes, you are right, for the small UI for browsing annotations you can use axios (same library that I use in this client or use this client as it is (which includes a couple of ways to retrieve/search annotations from hypothes.is). Both options are good. If you need further help in this matter please reopen this issue or a new one.
